"use client"

import type React from "react"
import { createContext, useContext, useEffect, useState } from "react"

type Language = "en" | "ar"

interface LanguageContextType {
  language: Language
  toggleLanguage: () => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Navigation
    home: "Home",
    about: "About",
    skills: "Skills",
    services: "Services",
    projects: "Projects",
    experience: "Experience",
    education: "Education",
    achievements: "Achievements",
    testimonials: "Testimonials",
    contact: "Contact",
    cv: "CV",
    linktree: "Linktree",

    // Hero Section
    heroTitle: "Momen Tarek",
    heroDescription:
      "Artificial intelligence student with a data science focus seeking a role in an impactful organization. Possessing 4 years of experience in Java, Python, and C++, and 3 years in writing efficient code. Fluent in English, German and Spanish. Detail-oriented, organized, and customer-focused with experience in demanding environments. Forward-thinking intern pursuing a software degree, capable of handling multiple projects, and skilled in design software.",
    viewProjects: "View Projects",
    contactMe: "Contact Me",

    // Skills Section
    skillsTitle: "Skills & Expertise",
    aiMachineLearning: "AI & Machine Learning",
    immersiveTech: "Immersive Technologies",
    softwareDev: "Software Development",
    creativeDesign: "Creative Design",

    // Services Section
    servicesTitle: "Services I Offer",
    servicesSubtitle:
      "Specialized expertise and solutions to help you achieve your goals, leveraging my experience in AI, data science, and development.",
    aiMlTitle: "AI & Machine Learning",
    aiMlDesc:
      "Custom AI solutions to solve complex problems and make predictions. From simple regression models to complex deep learning architectures.",
    dataAnalysisTitle: "Data Analysis & Visualization",
    dataAnalysisDesc:
      "Transform raw data into actionable insights with comprehensive analysis and stunning visualizations using Python, R, SQL, Power BI, and Tableau.",
    webMobileTitle: "Web & Mobile Development",
    webMobileDesc:
      "Modern, responsive applications that showcase your data and analytics. Custom solutions using the latest technologies for performance and usability.",
    uiUxTitle: "UI/UX & Graphic Design",
    uiUxDesc:
      "Creative design solutions with a strong foundation in design principles. Expert in Adobe Creative Suite, Figma, and Canva for digital and print media.",
    discussProject: "Discuss Your Project",

    // Projects Section
    projectsTitle: "Featured Projects",
    projectsSubtitle:
      "Explore my portfolio of over 50 projects spanning AI, machine learning, web development, and more. Each project demonstrates my technical skills and problem-solving abilities.",
    viewMoreGithub: "View More on GitHub",

    // Experience Section
    experienceTitle: "Professional Experience",
    experienceSubtitle:
      "My journey through various roles has equipped me with a diverse skill set and valuable industry experience.",
    viewFullResume: "View Full Resume",

    // Education Section
    educationTitle: "Education & Courses",
    educationSubtitle: "My academic journey and continuous learning through specialized courses and certifications.",
    formalEducation: "Formal Education",
    additionalCourses: "Additional Courses & Certifications",
    certified: "Certified",

    // Achievements Section
    achievementsTitle: "Achievements & Recognition",
    achievementsSubtitle:
      "Milestones and recognition that highlight my dedication to excellence in academics, leadership, and professional growth.",

    // Testimonials Section
    testimonialsTitle: "What People Say",
    testimonialsSubtitle:
      "Feedback from professors, colleagues, and clients who have worked with me on various projects and initiatives.",

    // Contact Section
    contactTitle: "Get in Touch",
    contactSubtitle: "Feel free to reach out for collaborations, opportunities, or just to say hello!",
    contactInfo: "Contact Information",
    contactDescription:
      "Feel free to reach out to me for collaboration, job opportunities, or just to say hello. I'm always open to discussing new projects and ideas.",
    sendMessage: "Send a Message",
    name: "Name",
    email: "Email",
    message: "Message",
    sendMessageBtn: "Send Message",
    visitLinktree: "Visit My Linktree",

    // Footer
    quickLinks: "Quick Links",
    connect: "Connect",
    madeWith: "Made with",
    allRightsReserved: "All rights reserved.",
    scrollToTop: "Scroll to top",

    // CV Page
    cvTitle: "Curriculum Vitae",
    cvSubtitle: "Download my complete CV or contact me directly for any opportunities or collaborations.",
    downloadCV: "Download CV",
    aiDeveloper: "AI Developer & Data Scientist",
    phone: "Phone",
    location: "Location",
    summary: "Summary",
    contactMeSection: "Contact Me",
    contactMeDescription:
      "I'm always open to new opportunities and collaborations. Feel free to reach out to me via email or phone, or connect with me on my social media profiles.",

    // Common
    loading: "Loading...",
    error: "Error",
    success: "Success",
    close: "Close",
    open: "Open",
    save: "Save",
    cancel: "Cancel",
    submit: "Submit",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    remove: "Remove",
    update: "Update",
    create: "Create",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    clear: "Clear",
    reset: "Reset",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    ok: "OK",
    back: "Back",
    next: "Next",
    previous: "Previous",
    finish: "Finish",
    done: "Done",
    continue: "Continue",
    skip: "Skip",
    retry: "Retry",
    refresh: "Refresh",
    reload: "Reload",
    print: "Print",
    download: "Download",
    upload: "Upload",
    share: "Share",
    copy: "Copy",
    paste: "Paste",
    cut: "Cut",
    undo: "Undo",
    redo: "Redo",
    select: "Select",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    expand: "Expand",
    collapse: "Collapse",
    show: "Show",
    hide: "Hide",
    view: "View",
    preview: "Preview",
    fullscreen: "Fullscreen",
    minimize: "Minimize",
    maximize: "Maximize",
    restore: "Restore",
    help: "Help",
    about: "About",
    settings: "Settings",
    preferences: "Preferences",
    profile: "Profile",
    account: "Account",
    login: "Login",
    logout: "Logout",
    register: "Register",
    signup: "Sign Up",
    signin: "Sign In",
    forgotPassword: "Forgot Password",
    resetPassword: "Reset Password",
    changePassword: "Change Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    currentPassword: "Current Password",
    username: "Username",
    password: "Password",
    rememberMe: "Remember Me",
    staySignedIn: "Stay Signed In",
    signOut: "Sign Out",
    welcome: "Welcome",
    goodbye: "Goodbye",
    hello: "Hello",
    hi: "Hi",
    thanks: "Thanks",
    thankYou: "Thank You",
    youreWelcome: "You're Welcome",
    please: "Please",
    sorry: "Sorry",
    excuse: "Excuse",
    pardon: "Pardon",
    congratulations: "Congratulations",
    goodLuck: "Good Luck",
    goodJob: "Good Job",
    wellDone: "Well Done",
    excellent: "Excellent",
    great: "Great",
    good: "Good",
    bad: "Bad",
    terrible: "Terrible",
    awesome: "Awesome",
    amazing: "Amazing",
    wonderful: "Wonderful",
    fantastic: "Fantastic",
    incredible: "Incredible",
    outstanding: "Outstanding",
    remarkable: "Remarkable",
    impressive: "Impressive",
    brilliant: "Brilliant",
    perfect: "Perfect",
    flawless: "Flawless",
    superb: "Superb",
    magnificent: "Magnificent",
    marvelous: "Marvelous",
    splendid: "Splendid",
    fabulous: "Fabulous",
    terrific: "Terrific",
    tremendous: "Tremendous",
    phenomenal: "Phenomenal",
    exceptional: "Exceptional",
    extraordinary: "Extraordinary",
    unbelievable: "Unbelievable",
    unreal: "Unreal",
    mindBlowing: "Mind-blowing",
    breathtaking: "Breathtaking",
    stunning: "Stunning",
    gorgeous: "Gorgeous",
    beautiful: "Beautiful",
    lovely: "Lovely",
    pretty: "Pretty",
    cute: "Cute",
    adorable: "Adorable",
    charming: "Charming",
    elegant: "Elegant",
    graceful: "Graceful",
    stylish: "Stylish",
    fashionable: "Fashionable",
    trendy: "Trendy",
    modern: "Modern",
    contemporary: "Contemporary",
    classic: "Classic",
    traditional: "Traditional",
    vintage: "Vintage",
    retro: "Retro",
    antique: "Antique",
    old: "Old",
    new: "New",
    fresh: "Fresh",
    recent: "Recent",
    latest: "Latest",
    current: "Current",
    updated: "Updated",
    revised: "Revised",
    improved: "Improved",
    enhanced: "Enhanced",
    upgraded: "Upgraded",
    advanced: "Advanced",
    sophisticated: "Sophisticated",
    complex: "Complex",
    simple: "Simple",
    easy: "Easy",
    difficult: "Difficult",
    hard: "Hard",
    challenging: "Challenging",
    tough: "Tough",
    rough: "Rough",
    smooth: "Smooth",
    soft: "Soft",
    gentle: "Gentle",
    mild: "Mild",
    strong: "Strong",
    powerful: "Powerful",
    weak: "Weak",
    fragile: "Fragile",
    delicate: "Delicate",
    robust: "Robust",
    sturdy: "Sturdy",
    solid: "Solid",
    stable: "Stable",
    secure: "Secure",
    safe: "Safe",
    dangerous: "Dangerous",
    risky: "Risky",
    hazardous: "Hazardous",
    harmful: "Harmful",
    beneficial: "Beneficial",
    useful: "Useful",
    helpful: "Helpful",
    valuable: "Valuable",
    important: "Important",
    significant: "Significant",
    relevant: "Relevant",
    appropriate: "Appropriate",
    suitable: "Suitable",
    proper: "Proper",
    correct: "Correct",
    right: "Right",
    wrong: "Wrong",
    incorrect: "Incorrect",
    false: "False",
    true: "True",
    real: "Real",
    fake: "Fake",
    genuine: "Genuine",
    authentic: "Authentic",
    original: "Original",
    unique: "Unique",
    special: "Special",
    rare: "Rare",
    common: "Common",
    usual: "Usual",
    normal: "Normal",
    regular: "Regular",
    standard: "Standard",
    basic: "Basic",
    fundamental: "Fundamental",
    essential: "Essential",
    necessary: "Necessary",
    required: "Required",
    optional: "Optional",
    available: "Available",
    unavailable: "Unavailable",
    accessible: "Accessible",
    inaccessible: "Inaccessible",
    visible: "Visible",
    invisible: "Invisible",
    hidden: "Hidden",
    obvious: "Obvious",
    clear: "Clear",
    unclear: "Unclear",
    confusing: "Confusing",
    complicated: "Complicated",
    straightforward: "Straightforward",
    direct: "Direct",
    indirect: "Indirect",
    immediate: "Immediate",
    instant: "Instant",
    quick: "Quick",
    fast: "Fast",
    rapid: "Rapid",
    slow: "Slow",
    gradual: "Gradual",
    sudden: "Sudden",
    unexpected: "Unexpected",
    surprising: "Surprising",
    shocking: "Shocking",
    amazing: "Amazing",
    astonishing: "Astonishing",
    remarkable: "Remarkable",
    notable: "Notable",
    noteworthy: "Noteworthy",
    memorable: "Memorable",
    unforgettable: "Unforgettable",
    forgettable: "Forgettable",
    interesting: "Interesting",
    boring: "Boring",
    exciting: "Exciting",
    thrilling: "Thrilling",
    fun: "Fun",
    enjoyable: "Enjoyable",
    pleasant: "Pleasant",
    unpleasant: "Unpleasant",
    comfortable: "Comfortable",
    uncomfortable: "Uncomfortable",
    convenient: "Convenient",
    inconvenient: "Inconvenient",
    practical: "Practical",
    impractical: "Impractical",
    logical: "Logical",
    illogical: "Illogical",
    reasonable: "Reasonable",
    unreasonable: "Unreasonable",
    sensible: "Sensible",
    nonsensical: "Nonsensical",
    wise: "Wise",
    foolish: "Foolish",
    smart: "Smart",
    clever: "Clever",
    intelligent: "Intelligent",
    stupid: "Stupid",
    dumb: "Dumb",
    ignorant: "Ignorant",
    knowledgeable: "Knowledgeable",
    educated: "Educated",
    uneducated: "Uneducated",
    experienced: "Experienced",
    inexperienced: "Inexperienced",
    skilled: "Skilled",
    unskilled: "Unskilled",
    talented: "Talented",
    untalented: "Untalented",
    gifted: "Gifted",
    creative: "Creative",
    innovative: "Innovative",
    original: "Original",
    imaginative: "Imaginative",
    artistic: "Artistic",
    technical: "Technical",
    scientific: "Scientific",
    mathematical: "Mathematical",
    analytical: "Analytical",
    critical: "Critical",
    objective: "Objective",
    subjective: "Subjective",
    neutral: "Neutral",
    biased: "Biased",
    fair: "Fair",
    unfair: "Unfair",
    just: "Just",
    unjust: "Unjust",
    equal: "Equal",
    unequal: "Unequal",
    balanced: "Balanced",
    unbalanced: "Unbalanced",
    consistent: "Consistent",
    inconsistent: "Inconsistent",
    reliable: "Reliable",
    unreliable: "Unreliable",
    dependable: "Dependable",
    undependable: "Undependable",
    trustworthy: "Trustworthy",
    untrustworthy: "Untrustworthy",
    honest: "Honest",
    dishonest: "Dishonest",
    sincere: "Sincere",
    insincere: "Insincere",
    genuine: "Genuine",
    fake: "Fake",
    real: "Real",
    artificial: "Artificial",
    natural: "Natural",
    unnatural: "Unnatural",
    organic: "Organic",
    synthetic: "Synthetic",
    pure: "Pure",
    impure: "Impure",
    clean: "Clean",
    dirty: "Dirty",
    fresh: "Fresh",
    stale: "Stale",
    new: "New",
    old: "Old",
    young: "Young",
    mature: "Mature",
    immature: "Immature",
    adult: "Adult",
    child: "Child",
    baby: "Baby",
    infant: "Infant",
    toddler: "Toddler",
    teenager: "Teenager",
    adolescent: "Adolescent",
    youth: "Youth",
    elderly: "Elderly",
    senior: "Senior",
    junior: "Junior",
    beginner: "Beginner",
    novice: "Novice",
    amateur: "Amateur",
    professional: "Professional",
    expert: "Expert",
    specialist: "Specialist",
    master: "Master",
    apprentice: "Apprentice",
    student: "Student",
    teacher: "Teacher",
    instructor: "Instructor",
    professor: "Professor",
    doctor: "Doctor",
    nurse: "Nurse",
    engineer: "Engineer",
    developer: "Developer",
    programmer: "Programmer",
    designer: "Designer",
    artist: "Artist",
    writer: "Writer",
    author: "Author",
    journalist: "Journalist",
    reporter: "Reporter",
    editor: "Editor",
    publisher: "Publisher",
    manager: "Manager",
    director: "Director",
    supervisor: "Supervisor",
    employee: "Employee",
    worker: "Worker",
    staff: "Staff",
    team: "Team",
    group: "Group",
    organization: "Organization",
    company: "Company",
    business: "Business",
    corporation: "Corporation",
    enterprise: "Enterprise",
    firm: "Firm",
    agency: "Agency",
    institution: "Institution",
    establishment: "Establishment",
    foundation: "Foundation",
    association: "Association",
    society: "Society",
    club: "Club",
    union: "Union",
    alliance: "Alliance",
    partnership: "Partnership",
    collaboration: "Collaboration",
    cooperation: "Cooperation",
    teamwork: "Teamwork",
    unity: "Unity",
    harmony: "Harmony",
    peace: "Peace",
    war: "War",
    conflict: "Conflict",
    dispute: "Dispute",
    argument: "Argument",
    disagreement: "Disagreement",
    agreement: "Agreement",
    consensus: "Consensus",
    compromise: "Compromise",
    negotiation: "Negotiation",
    discussion: "Discussion",
    conversation: "Conversation",
    dialogue: "Dialogue",
    communication: "Communication",
    interaction: "Interaction",
    relationship: "Relationship",
    connection: "Connection",
    bond: "Bond",
    link: "Link",
    tie: "Tie",
    attachment: "Attachment",
    association: "Association",
    affiliation: "Affiliation",
    membership: "Membership",
    participation: "Participation",
    involvement: "Involvement",
    engagement: "Engagement",
    commitment: "Commitment",
    dedication: "Dedication",
    devotion: "Devotion",
    loyalty: "Loyalty",
    faithfulness: "Faithfulness",
    reliability: "Reliability",
    dependability: "Dependability",
    consistency: "Consistency",
    stability: "Stability",
    security: "Security",
    safety: "Safety",
    protection: "Protection",
    defense: "Defense",
    guard: "Guard",
    shield: "Shield",
    barrier: "Barrier",
    wall: "Wall",
    fence: "Fence",
    border: "Border",
    boundary: "Boundary",
    limit: "Limit",
    restriction: "Restriction",
    constraint: "Constraint",
    limitation: "Limitation",
    freedom: "Freedom",
    liberty: "Liberty",
    independence: "Independence",
    autonomy: "Autonomy",
    sovereignty: "Sovereignty",
    authority: "Authority",
    power: "Power",
    control: "Control",
    command: "Command",
    leadership: "Leadership",
    management: "Management",
    administration: "Administration",
    governance: "Governance",
    government: "Government",
    politics: "Politics",
    policy: "Policy",
    law: "Law",
    rule: "Rule",
    regulation: "Regulation",
    guideline: "Guideline",
    instruction: "Instruction",
    direction: "Direction",
    guidance: "Guidance",
    advice: "Advice",
    suggestion: "Suggestion",
    recommendation: "Recommendation",
    proposal: "Proposal",
    idea: "Idea",
    concept: "Concept",
    notion: "Notion",
    thought: "Thought",
    opinion: "Opinion",
    view: "View",
    perspective: "Perspective",
    viewpoint: "Viewpoint",
    standpoint: "Standpoint",
    position: "Position",
    stance: "Stance",
    attitude: "Attitude",
    approach: "Approach",
    method: "Method",
    technique: "Technique",
    strategy: "Strategy",
    plan: "Plan",
    scheme: "Scheme",
    program: "Program",
    project: "Project",
    initiative: "Initiative",
    campaign: "Campaign",
    mission: "Mission",
    goal: "Goal",
    objective: "Objective",
    target: "Target",
    aim: "Aim",
    purpose: "Purpose",
    intention: "Intention",
    motive: "Motive",
    reason: "Reason",
    cause: "Cause",
    factor: "Factor",
    element: "Element",
    component: "Component",
    part: "Part",
    piece: "Piece",
    section: "Section",
    segment: "Segment",
    portion: "Portion",
    fraction: "Fraction",
    percentage: "Percentage",
    ratio: "Ratio",
    proportion: "Proportion",
    scale: "Scale",
    size: "Size",
    dimension: "Dimension",
    measurement: "Measurement",
    quantity: "Quantity",
    amount: "Amount",
    number: "Number",
    count: "Count",
    total: "Total",
    sum: "Sum",
    average: "Average",
    mean: "Mean",
    median: "Median",
    mode: "Mode",
    range: "Range",
    minimum: "Minimum",
    maximum: "Maximum",
    limit: "Limit",
    boundary: "Boundary",
    edge: "Edge",
    border: "Border",
    margin: "Margin",
    space: "Space",
    gap: "Gap",
    distance: "Distance",
    length: "Length",
    width: "Width",
    height: "Height",
    depth: "Depth",
    thickness: "Thickness",
    weight: "Weight",
    mass: "Mass",
    volume: "Volume",
    capacity: "Capacity",
    area: "Area",
    surface: "Surface",
    shape: "Shape",
    form: "Form",
    structure: "Structure",
    pattern: "Pattern",
    design: "Design",
    layout: "Layout",
    arrangement: "Arrangement",
    organization: "Organization",
    order: "Order",
    sequence: "Sequence",
    series: "Series",
    chain: "Chain",
    cycle: "Cycle",
    process: "Process",
    procedure: "Procedure",
    operation: "Operation",
    function: "Function",
    activity: "Activity",
    action: "Action",
    behavior: "Behavior",
    conduct: "Conduct",
    performance: "Performance",
    execution: "Execution",
    implementation: "Implementation",
    application: "Application",
    usage: "Usage",
    use: "Use",
    utilization: "Utilization",
    employment: "Employment",
    work: "Work",
    job: "Job",
    task: "Task",
    duty: "Duty",
    responsibility: "Responsibility",
    obligation: "Obligation",
    requirement: "Requirement",
    necessity: "Necessity",
    need: "Need",
    demand: "Demand",
    request: "Request",
    desire: "Desire",
    want: "Want",
    wish: "Wish",
    hope: "Hope",
    expectation: "Expectation",
    anticipation: "Anticipation",
    prediction: "Prediction",
    forecast: "Forecast",
    projection: "Projection",
    estimate: "Estimate",
    calculation: "Calculation",
    computation: "Computation",
    analysis: "Analysis",
    examination: "Examination",
    investigation: "Investigation",
    research: "Research",
    study: "Study",
    survey: "Survey",
    review: "Review",
    evaluation: "Evaluation",
    assessment: "Assessment",
    judgment: "Judgment",
    decision: "Decision",
    choice: "Choice",
    selection: "Selection",
    option: "Option",
    alternative: "Alternative",
    possibility: "Possibility",
    opportunity: "Opportunity",
    chance: "Chance",
    probability: "Probability",
    likelihood: "Likelihood",
    risk: "Risk",
    danger: "Danger",
    threat: "Threat",
    hazard: "Hazard",
    problem: "Problem",
    issue: "Issue",
    challenge: "Challenge",
    difficulty: "Difficulty",
    obstacle: "Obstacle",
    barrier: "Barrier",
    hindrance: "Hindrance",
    impediment: "Impediment",
    complication: "Complication",
    complexity: "Complexity",
    simplicity: "Simplicity",
    ease: "Ease",
    convenience: "Convenience",
    comfort: "Comfort",
    pleasure: "Pleasure",
    enjoyment: "Enjoyment",
    satisfaction: "Satisfaction",
    happiness: "Happiness",
    joy: "Joy",
    delight: "Delight",
    excitement: "Excitement",
    enthusiasm: "Enthusiasm",
    passion: "Passion",
    love: "Love",
    affection: "Affection",
    fondness: "Fondness",
    liking: "Liking",
    preference: "Preference",
    favor: "Favor",
    support: "Support",
    assistance: "Assistance",
    help: "Help",
    aid: "Aid",
    service: "Service",
    benefit: "Benefit",
    advantage: "Advantage",
    profit: "Profit",
    gain: "Gain",
    income: "Income",
    revenue: "Revenue",
    earnings: "Earnings",
    salary: "Salary",
    wage: "Wage",
    payment: "Payment",
    compensation: "Compensation",
    reward: "Reward",
    prize: "Prize",
    award: "Award",
    recognition: "Recognition",
    acknowledgment: "Acknowledgment",
    appreciation: "Appreciation",
    gratitude: "Gratitude",
    thanks: "Thanks",
    credit: "Credit",
    praise: "Praise",
    compliment: "Compliment",
    approval: "Approval",
    endorsement: "Endorsement",
    recommendation: "Recommendation",
    reference: "Reference",
    testimonial: "Testimonial",
    review: "Review",
    feedback: "Feedback",
    comment: "Comment",
    remark: "Remark",
    observation: "Observation",
    note: "Note",
    notice: "Notice",
    announcement: "Announcement",
    declaration: "Declaration",
    statement: "Statement",
    claim: "Claim",
    assertion: "Assertion",
    argument: "Argument",
    point: "Point",
    fact: "Fact",
    truth: "Truth",
    reality: "Reality",
    actuality: "Actuality",
    existence: "Existence",
    presence: "Presence",
    absence: "Absence",
    lack: "Lack",
    shortage: "Shortage",
    deficit: "Deficit",
    scarcity: "Scarcity",
    abundance: "Abundance",
    plenty: "Plenty",
    surplus: "Surplus",
    excess: "Excess",
    overflow: "Overflow",
    increase: "Increase",
    growth: "Growth",
    expansion: "Expansion",
    development: "Development",
    progress: "Progress",
    advancement: "Advancement",
    improvement: "Improvement",
    enhancement: "Enhancement",
    upgrade: "Upgrade",
    update: "Update",
    revision: "Revision",
    modification: "Modification",
    change: "Change",
    alteration: "Alteration",
    transformation: "Transformation",
    conversion: "Conversion",
    transition: "Transition",
    shift: "Shift",
    move: "Move",
    movement: "Movement",
    motion: "Motion",
    action: "Action",
    activity: "Activity",
    operation: "Operation",
    function: "Function",
    performance: "Performance",
    execution: "Execution",
    implementation: "Implementation",
    application: "Application",
    practice: "Practice",
    exercise: "Exercise",
    training: "Training",
    education: "Education",
    learning: "Learning",
    teaching: "Teaching",
    instruction: "Instruction",
    guidance: "Guidance",
    direction: "Direction",
    leadership: "Leadership",
    management: "Management",
    supervision: "Supervision",
    oversight: "Oversight",
    control: "Control",
    regulation: "Regulation",
    administration: "Administration",
    governance: "Governance",
    organization: "Organization",
    coordination: "Coordination",
    collaboration: "Collaboration",
    cooperation: "Cooperation",
    partnership: "Partnership",
    alliance: "Alliance",
    union: "Union",
    association: "Association",
    relationship: "Relationship",
    connection: "Connection",
    link: "Link",
    bond: "Bond",
    tie: "Tie",
    attachment: "Attachment",
    affiliation: "Affiliation",
    membership: "Membership",
    participation: "Participation",
    involvement: "Involvement",
    engagement: "Engagement",
    interaction: "Interaction",
    communication: "Communication",
    conversation: "Conversation",
    discussion: "Discussion",
    dialogue: "Dialogue",
    exchange: "Exchange",
    transfer: "Transfer",
    transmission: "Transmission",
    delivery: "Delivery",
    distribution: "Distribution",
    supply: "Supply",
    provision: "Provision",
    offering: "Offering",
    presentation: "Presentation",
    display: "Display",
    exhibition: "Exhibition",
    demonstration: "Demonstration",
    show: "Show",
    performance: "Performance",
    event: "Event",
    occasion: "Occasion",
    ceremony: "Ceremony",
    celebration: "Celebration",
    festival: "Festival",
    party: "Party",
    gathering: "Gathering",
    meeting: "Meeting",
    conference: "Conference",
    seminar: "Seminar",
    workshop: "Workshop",
    session: "Session",
    class: "Class",
    course: "Course",
    program: "Program",
    curriculum: "Curriculum",
    syllabus: "Syllabus",
    schedule: "Schedule",
    timetable: "Timetable",
    agenda: "Agenda",
    plan: "Plan",
    strategy: "Strategy",
    approach: "Approach",
    method: "Method",
    technique: "Technique",
    procedure: "Procedure",
    process: "Process",
    system: "System",
    mechanism: "Mechanism",
    device: "Device",
    tool: "Tool",
    instrument: "Instrument",
    equipment: "Equipment",
    apparatus: "Apparatus",
    machine: "Machine",
    technology: "Technology",
    innovation: "Innovation",
    invention: "Invention",
    creation: "Creation",
    production: "Production",
    manufacturing: "Manufacturing",
    construction: "Construction",
    building: "Building",
    development: "Development",
    establishment: "Establishment",
    foundation: "Foundation",
    formation: "Formation",
    organization: "Organization",
    structure: "Structure",
    framework: "Framework",
    architecture: "Architecture",
    design: "Design",
    pattern: "Pattern",
    model: "Model",
    template: "Template",
    format: "Format",
    style: "Style",
    fashion: "Fashion",
    trend: "Trend",
    custom: "Custom",
    tradition: "Tradition",
    culture: "Culture",
    heritage: "Heritage",
    legacy: "Legacy",
    history: "History",
    past: "Past",
    present: "Present",
    future: "Future",
    time: "Time",
    period: "Period",
    era: "Era",
    age: "Age",
    generation: "Generation",
    century: "Century",
    decade: "Decade",
    year: "Year",
    month: "Month",
    week: "Week",
    day: "Day",
    hour: "Hour",
    minute: "Minute",
    second: "Second",
    moment: "Moment",
    instant: "Instant",
    duration: "Duration",
    length: "Length",
    span: "Span",
    interval: "Interval",
    gap: "Gap",
    break: "Break",
    pause: "Pause",
    rest: "Rest",
    stop: "Stop",
    end: "End",
    finish: "Finish",
    conclusion: "Conclusion",
    completion: "Completion",
    termination: "Termination",
    closure: "Closure",
    beginning: "Beginning",
    start: "Start",
    commencement: "Commencement",
    initiation: "Initiation",
    launch: "Launch",
    opening: "Opening",
    introduction: "Introduction",
    preface: "Preface",
    prologue: "Prologue",
    foreword: "Foreword",
    prelude: "Prelude",
    preview: "Preview",
    overview: "Overview",
    summary: "Summary",
    synopsis: "Synopsis",
    abstract: "Abstract",
    outline: "Outline",
    sketch: "Sketch",
    draft: "Draft",
    version: "Version",
    edition: "Edition",
    copy: "Copy",
    duplicate: "Duplicate",
    replica: "Replica",
    reproduction: "Reproduction",
    imitation: "Imitation",
    simulation: "Simulation",
    model: "Model",
    example: "Example",
    instance: "Instance",
    case: "Case",
    situation: "Situation",
    circumstance: "Circumstance",
    condition: "Condition",
    state: "State",
    status: "Status",
    position: "Position",
    location: "Location",
    place: "Place",
    site: "Site",
    spot: "Spot",
    area: "Area",
    region: "Region",
    zone: "Zone",
    territory: "Territory",
    domain: "Domain",
    field: "Field",
    sphere: "Sphere",
    realm: "Realm",
    scope: "Scope",
    range: "Range",
    extent: "Extent",
    scale: "Scale",
    level: "Level",
    degree: "Degree",
    grade: "Grade",
    rank: "Rank",
    rating: "Rating",
    score: "Score",
    mark: "Mark",
    point: "Point",
    value: "Value",
    worth: "Worth",
    price: "Price",
    cost: "Cost",
    expense: "Expense",
    fee: "Fee",
    charge: "Charge",
    rate: "Rate",
    amount: "Amount",
    sum: "Sum",
    total: "Total",
    quantity: "Quantity",
    number: "Number",
    figure: "Figure",
    statistic: "Statistic",
    data: "Data",
    information: "Information",
    knowledge: "Knowledge",
    wisdom: "Wisdom",
    understanding: "Understanding",
    comprehension: "Comprehension",
    awareness: "Awareness",
    consciousness: "Consciousness",
    perception: "Perception",
    recognition: "Recognition",
    realization: "Realization",
    discovery: "Discovery",
    finding: "Finding",
    result: "Result",
    outcome: "Outcome",
    consequence: "Consequence",
    effect: "Effect",
    impact: "Impact",
    influence: "Influence",
    power: "Power",
    force: "Force",
    strength: "Strength",
    energy: "Energy",
    effort: "Effort",
    attempt: "Attempt",
    try: "Try",
    endeavor: "Endeavor",
    struggle: "Struggle",
    fight: "Fight",
    battle: "Battle",
    war: "War",
    conflict: "Conflict",
    competition: "Competition",
    contest: "Contest",
    match: "Match",
    game: "Game",
    sport: "Sport",
    play: "Play",
    entertainment: "Entertainment",
    amusement: "Amusement",
    fun: "Fun",
    enjoyment: "Enjoyment",
    pleasure: "Pleasure",
    happiness: "Happiness",
    joy: "Joy",
    satisfaction: "Satisfaction",
    contentment: "Contentment",
    fulfillment: "Fulfillment",
    achievement: "Achievement",
    accomplishment: "Accomplishment",
    success: "Success",
    victory: "Victory",
    triumph: "Triumph",
    win: "Win",
    defeat: "Defeat",
    loss: "Loss",
    failure: "Failure",
    mistake: "Mistake",
    error: "Error",
    fault: "Fault",
    flaw: "Flaw",
    defect: "Defect",
    problem: "Problem",
    issue: "Issue",
    concern: "Concern",
    worry: "Worry",
    anxiety: "Anxiety",
    fear: "Fear",
    doubt: "Doubt",
    uncertainty: "Uncertainty",
    confusion: "Confusion",
    misunderstanding: "Misunderstanding",
    clarity: "Clarity",
    understanding: "Understanding",
    knowledge: "Knowledge",
    information: "Information",
    data: "Data",
    facts: "Facts",
    details: "Details",
    specifics: "Specifics",
    particulars: "Particulars",
    features: "Features",
    characteristics: "Characteristics",
    qualities: "Qualities",
    attributes: "Attributes",
    properties: "Properties",
    aspects: "Aspects",
    elements: "Elements",
    components: "Components",
    parts: "Parts",
    pieces: "Pieces",
    sections: "Sections",
    segments: "Segments",
    divisions: "Divisions",
    categories: "Categories",
    types: "Types",
    kinds: "Kinds",
    varieties: "Varieties",
    forms: "Forms",
    shapes: "Shapes",
    sizes: "Sizes",
    colors: "Colors",
    materials: "Materials",
    substances: "Substances",
    contents: "Contents",
    ingredients: "Ingredients",
    components: "Components",
    elements: "Elements",
    factors: "Factors",
    variables: "Variables",
    parameters: "Parameters",
    criteria: "Criteria",
    standards: "Standards",
    requirements: "Requirements",
    specifications: "Specifications",
    guidelines: "Guidelines",
    rules: "Rules",
    regulations: "Regulations",
    laws: "Laws",
    policies: "Policies",
    procedures: "Procedures",
    processes: "Processes",
    methods: "Methods",
    techniques: "Techniques",
    approaches: "Approaches",
    strategies: "Strategies",
    plans: "Plans",
    schemes: "Schemes",
    programs: "Programs",
    projects: "Projects",
    initiatives: "Initiatives",
    campaigns: "Campaigns",
    missions: "Missions",
    goals: "Goals",
    objectives: "Objectives",
    targets: "Targets",
    aims: "Aims",
    purposes: "Purposes",
    intentions: "Intentions",
    motives: "Motives",
    reasons: "Reasons",
    causes: "Causes",
    origins: "Origins",
    sources: "Sources",
    roots: "Roots",
    foundations: "Foundations",
    bases: "Bases",
    grounds: "Grounds",
    principles: "Principles",
    concepts: "Concepts",
    ideas: "Ideas",
    thoughts: "Thoughts",
    opinions: "Opinions",
    views: "Views",
    perspectives: "Perspectives",
    viewpoints: "Viewpoints",
    standpoints: "Standpoints",
    positions: "Positions",
    stances: "Stances",
    attitudes: "Attitudes",
    beliefs: "Beliefs",
    values: "Values",
    morals: "Morals",
    ethics: "Ethics",
    standards: "Standards",
    norms: "Norms",
    customs: "Customs",
    traditions: "Traditions",
    practices: "Practices",
    habits: "Habits",
    routines: "Routines",
    patterns: "Patterns",
    behaviors: "Behaviors",
    actions: "Actions",
    activities: "Activities",
    operations: "Operations",
    functions: "Functions",
    roles: "Roles",
    duties: "Duties",
    responsibilities: "Responsibilities",
    obligations: "Obligations",
    commitments: "Commitments",
    promises: "Promises",
    agreements: "Agreements",
    contracts: "Contracts",
    deals: "Deals",
    arrangements: "Arrangements",
    plans: "Plans",
    preparations: "Preparations",
    provisions: "Provisions",
    supplies: "Supplies",
    resources: "Resources",
    materials: "Materials",
    tools: "Tools",
    equipment: "Equipment",
    facilities: "Facilities",
    services: "Services",
    support: "Support",
    assistance: "Assistance",
    help: "Help",
    aid: "Aid",
    guidance: "Guidance",
    advice: "Advice",
    suggestions: "Suggestions",
    recommendations: "Recommendations",
    proposals: "Proposals",
    offers: "Offers",
    opportunities: "Opportunities",
    chances: "Chances",
    possibilities: "Possibilities",
    options: "Options",
    alternatives: "Alternative",
    choices: "Choices",
    selections: "Selections",
    decisions: "Decisions",
    judgments: "Judgments",
    evaluations: "Evaluations",
    assessments: "Assessments",
    analyses: "Analyses",
    examinations: "Examinations",
    investigations: "Investigations",
    studies: "Studies",
    research: "Research",
    surveys: "Surveys",
    reviews: "Reviews",
    reports: "Reports",
    documents: "Documents",
    records: "Records",
    files: "Files",
    papers: "Papers",
    forms: "Forms",
    applications: "Applications",
    requests: "Requests",
    submissions: "Submissions",
    proposals: "Proposals",
    presentations: "Presentations",
    demonstrations: "Demonstrations",
    exhibitions: "Exhibitions",
    displays: "Displays",
    shows: "Shows",
    performances: "Performances",
    events: "Events",
    occasions: "Occasions",
    ceremonies: "Ceremonies",
    celebrations: "Celebrations",
    festivals: "Festivals",
    parties: "Parties",
    gatherings: "Gatherings",
    meetings: "Meetings",
    conferences: "Conferences",
    seminars: "Seminars",
    workshops: "Workshops",
    sessions: "Sessions",
    classes: "Classes",
    courses: "Courses",
    programs: "Programs",
    curricula: "Curricula",
    syllabi: "Syllabi",
    schedules: "Schedules",
    timetables: "Timetables",
    agendas: "Agendas",
    calendars: "Calendars",
    dates: "Dates",
    times: "Times",
    periods: "Periods",
    durations: "Durations",
    intervals: "Intervals",
    spans: "Spans",
    lengths: "Lengths",
    distances: "Distances",
    spaces: "Spaces",
    gaps: "Gaps",
    breaks: "Breaks",
    pauses: "Pauses",
    rests: "Rests",
    stops: "Stops",
    ends: "Ends",
    finishes: "Finishes",
    conclusions: "Conclusions",
    completions: "Completions",
    terminations: "Terminations",
    closures: "Closures",
    beginnings: "Beginnings",
    starts: "Starts",
    commencements: "Commencements",
    initiations: "Initiations",
    launches: "Launches",
    openings: "Openings",
    introductions: "Introductions",
    prefaces: "Prefaces",
    prologues: "Prologues",
    forewords: "Forewords",
    preludes: "Preludes",
    previews: "Previews",
    overviews: "Overviews",
    summaries: "Summaries",
    synopses: "Synopses",
    abstracts: "Abstracts",
    outlines: "Outlines",
    sketches: "Sketches",
    drafts: "Drafts",
    versions: "Versions",
    editions: "Editions",
    copies: "Copies",
    duplicates: "Duplicates",
    replicas: "Replicas",
    reproductions: "Reproductions",
    imitations: "Imitations",
    simulations: "Simulations",
    models: "Models",
    examples: "Examples",
    instances: "Instances",
    cases: "Cases",
    situations: "Situations",
    circumstances: "Circumstances",
    conditions: "Conditions",
    states: "States",
    statuses: "Statuses",
    positions: "Positions",
    locations: "Locations",
    places: "Places",
    sites: "Sites",
    spots: "Spots",
    areas: "Areas",
    regions: "Regions",
    zones: "Zones",
    territories: "Territories",
    domains: "Domains",
    fields: "Fields",
    spheres: "Spheres",
    realms: "Realms",
    scopes: "Scopes",
    ranges: "Ranges",
    extents: "Extents",
    scales: "Scales",
    levels: "Levels",
    degrees: "Degrees",
    grades: "Grades",
    ranks: "Ranks",
    ratings: "Ratings",
    scores: "Scores",
    marks: "Marks",
    points: "Points",
    values: "Values",
    worths: "Worths",
    prices: "Prices",
    costs: "Costs",
    expenses: "Expenses",
    fees: "Fees",
    charges: "Charges",
    rates: "Rates",
    amounts: "Amounts",
    sums: "Sums",
    totals: "Totals",
    quantities: "Quantities",
    numbers: "Numbers",
    figures: "Figures",
    statistics: "Statistics",
  },
  ar: {
    // Navigation
    home: "الرئيسية",
    about: "نبذة",
    skills: "المهارات",
    services: "الخدمات",
    projects: "المشاريع",
    experience: "الخبرة",
    education: "التعليم",
    achievements: "الإنجازات",
    testimonials: "الشهادات",
    contact: "التواصل",
    cv: "السيرة الذاتية",
    linktree: "روابطي",

    // Hero Section
    heroTitle: "مؤمن طارق",
    heroDescription:
      "طالب ذكاء اصطناعي متخصص في علوم البيانات يسعى للعمل في منظمة مؤثرة. يمتلك 4 سنوات من الخبرة في Java و Python و C++، و3 سنوات في كتابة الكود الفعال. يتقن الإنجليزية والألمانية والإسبانية. لديه سنتان من الخبرة في البيئات الصعبة، ويتميز بالدقة والتنظيم والتركيز على العملاء. متدرب طموح يسعى للحصول على درجة في البرمجيات، قادر على التعامل مع مشاريع متعددة، وماهر في برامج التصميم.",
    viewProjects: "عرض المشاريع",
    contactMe: "تواصل معي",

    // Skills Section
    skillsTitle: "المهارات والخبرات",
    aiMachineLearning: "الذكاء الاصطناعي والتعلم الآلي",
    immersiveTech: "التقنيات التفاعلية",
    softwareDev: "تطوير البرمجيات",
    creativeDesign: "التصميم الإبداعي",

    // Services Section
    servicesTitle: "الخدمات التي أقدمها",
    servicesSubtitle:
      "خبرة متخصصة وحلول لمساعدتك في تحقيق أهدافك، مستفيداً من خبرتي في الذكاء الاصطناعي وعلوم البيانات والتطوير.",
    aiMlTitle: "الذكاء الاصطناعي والتعلم الآلي",
    aiMlDesc:
      "حلول ذكاء اصطناعي مخصصة لحل المشاكل المعقدة والتنبؤات. من نماذج الانحدار البسيطة إلى هياكل التعلم العميق المعقدة.",
    dataAnalysisTitle: "تحليل البيانات والتصور",
    dataAnalysisDesc:
      "تحويل البيانات الخام إلى رؤى قابلة للتنفيذ مع تحليل شامل وتصورات مذهلة باستخدام Python و R و SQL و Power BI و Tableau.",
    webMobileTitle: "تطوير الويب والجوال",
    webMobileDesc:
      "تطبيقات حديثة ومتجاوبة تعرض بياناتك وتحليلاتك. حلول مخصصة باستخدام أحدث التقنيات للأداء وسهولة الاستخدام.",
    uiUxTitle: "تصميم واجهة المستخدم والجرافيك",
    uiUxDesc:
      "حلول تصميم إبداعية مع أساس قوي في مبادئ التصميم. خبير في Adobe Creative Suite و Figma و Canva للوسائط الرقمية والمطبوعة.",
    discussProject: "ناقش مشروعك",

    // Projects Section
    projectsTitle: "المشاريع المميزة",
    projectsSubtitle:
      "استكشف محفظتي التي تضم أكثر من 50 مشروعاً في الذكاء الاصطناعي والتعلم الآلي وتطوير الويب والمزيد. كل مشروع يُظهر مهاراتي التقنية وقدراتي في حل المشاكل.",
    viewMoreGithub: "عرض المزيد على GitHub",

    // Experience Section
    experienceTitle: "الخبرة المهنية",
    experienceSubtitle: "رحلتي عبر أدوار مختلفة زودتني بمجموعة مهارات متنوعة وخبرة صناعية قيمة.",
    viewFullResume: "عرض السيرة الذاتية الكاملة",

    // Education Section
    educationTitle: "التعليم والدورات",
    educationSubtitle: "رحلتي الأكاديمية والتعلم المستمر من خلال الدورات والشهادات المتخصصة.",
    formalEducation: "التعليم الرسمي",
    additionalCourses: "الدورات والشهادات الإضافية",
    certified: "معتمد",

    // Achievements Section
    achievementsTitle: "الإنجازات والتقدير",
    achievementsSubtitle: "المعالم والتقدير التي تسلط الضوء على تفاني في التميز في الأكاديميات والقيادة والنمو المهني.",

    // Testimonials Section
    testimonialsTitle: "ما يقوله الناس",
    testimonialsSubtitle: "تعليقات من الأساتذة والزملاء والعملاء الذين عملوا معي في مشاريع ومبادرات مختلفة.",

    // Contact Section
    contactTitle: "تواصل معي",
    contactSubtitle: "لا تتردد في التواصل للتعاون أو الفرص أو حتى لمجرد السلام!",
    contactInfo: "معلومات التواصل",
    contactDescription:
      "لا تتردد في التواصل معي للتعاون أو الفرص الوظيفية أو حتى لمجرد السلام. أنا دائماً منفتح لمناقشة مشاريع وأفكار جديدة.",
    sendMessage: "إرسال رسالة",
    name: "الاسم",
    email: "البريد الإلكتروني",
    message: "الرسالة",
    sendMessageBtn: "إرسال الرسالة",
    visitLinktree: "زيارة روابطي",

    // Footer
    quickLinks: "روابط سريعة",
    connect: "تواصل",
    madeWith: "صُنع بـ",
    allRightsReserved: "جميع الحقوق محفوظة.",
    scrollToTop: "العودة للأعلى",

    // CV Page
    cvTitle: "السيرة الذاتية",
    cvSubtitle: "حمل سيرتي الذاتية الكاملة أو تواصل معي مباشرة لأي فرص أو تعاون.",
    downloadCV: "تحميل السيرة الذاتية",
    aiDeveloper: "مطور ذكاء اصطناعي وعالم بيانات",
    phone: "الهاتف",
    location: "الموقع",
    summary: "الملخص",
    contactMeSection: "تواصل معي",
    contactMeDescription:
      "أنا دائماً منفتح للفرص الجديدة والتعاون. لا تتردد في التواصل معي عبر البريد الإلكتروني أو الهاتف، أو تواصل معي على ملفاتي الشخصية على وسائل التواصل الاجتماعي.",

    // Common
    loading: "جاري التحميل...",
    error: "خطأ",
    success: "نجح",
    close: "إغلاق",
    open: "فتح",
    save: "حفظ",
    cancel: "إلغاء",
    submit: "إرسال",
    edit: "تعديل",
    delete: "حذف",
    add: "إضافة",
    remove: "إزالة",
    update: "تحديث",
    create: "إنشاء",
    search: "بحث",
    filter: "تصفية",
    sort: "ترتيب",
    clear: "مسح",
    reset: "إعادة تعيين",
    confirm: "تأكيد",
    yes: "نعم",
    no: "لا",
    ok: "موافق",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    finish: "إنهاء",
    done: "تم",
    continue: "متابعة",
    skip: "تخطي",
    retry: "إعادة المحاولة",
    refresh: "تحديث",
    reload: "إعادة تحميل",
    print: "طباعة",
    download: "تحميل",
    upload: "رفع",
    share: "مشاركة",
    copy: "نسخ",
    paste: "لصق",
    cut: "قص",
    undo: "تراجع",
    redo: "إعادة",
    select: "اختيار",
    selectAll: "اختيار الكل",
    deselectAll: "إلغاء اختيار الكل",
    expand: "توسيع",
    collapse: "طي",
    show: "عرض",
    hide: "إخفاء",
    view: "عرض",
    preview: "معاينة",
    fullscreen: "ملء الشاشة",
    minimize: "تصغير",
    maximize: "تكبير",
    restore: "استعادة",
    help: "مساعدة",
    about: "حول",
    settings: "الإعدادات",
    preferences: "التفضيلات",
    profile: "الملف الشخصي",
    account: "الحساب",
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    register: "التسجيل",
    signup: "إنشاء حساب",
    signin: "تسجيل الدخول",
    forgotPassword: "نسيت كلمة المرور",
    resetPassword: "إعادة تعيين كلمة المرور",
    changePassword: "تغيير كلمة المرور",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    currentPassword: "كلمة المرور الحالية",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    rememberMe: "تذكرني",
    staySignedIn: "البقاء مسجلاً",
    signOut: "تسجيل الخروج",
    welcome: "مرحباً",
    goodbye: "وداعاً",
    hello: "أهلاً",
    hi: "مرحبا",
    thanks: "شكراً",
    thankYou: "شكراً لك",
    youreWelcome: "عفواً",
    please: "من فضلك",
    sorry: "آسف",
    excuse: "عذراً",
    pardon: "المعذرة",
    congratulations: "تهانينا",
    goodLuck: "حظاً سعيداً",
    goodJob: "عمل جيد",
    wellDone: "أحسنت",
    excellent: "ممتاز",
    great: "رائع",
    good: "جيد",
    bad: "سيء",
    terrible: "فظيع",
    awesome: "مذهل",
    amazing: "مدهش",
    wonderful: "رائع",
    fantastic: "خيالي",
    incredible: "لا يصدق",
    outstanding: "متميز",
    remarkable: "ملحوظ",
    impressive: "مثير للإعجاب",
    brilliant: "بارع",
    perfect: "مثالي",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "ar")) {
      setLanguage(savedLanguage)
      document.documentElement.dir = savedLanguage === "ar" ? "rtl" : "ltr"
      document.documentElement.lang = savedLanguage
    }
  }, [])

  const toggleLanguage = () => {
    const newLanguage = language === "en" ? "ar" : "en"
    setLanguage(newLanguage)
    document.documentElement.dir = newLanguage === "ar" ? "rtl" : "ltr"
    document.documentElement.lang = newLanguage
    localStorage.setItem("language", newLanguage)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, toggleLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
